import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Server-only modules that UI components must never import. Patterns use gitignore
// semantics: `**/` matches the `@/` alias and relative `../` imports, a match on a path
// also covers everything beneath it, and `.*` catches explicit extensions.
const serverOnly = (modulePath, role) => ({
  group: [`**/${modulePath}`, `**/${modulePath}.*`],
  message: `src/${modulePath} is server-only (${role}). Components must get this data from an API route instead.`,
});

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`; not ours to lint.
    "src/generated/**",
    // Agent worktrees are full checkouts of other branches.
    ".claude/**",
    // Retired one-off scripts, kept for reference and no longer run.
    "scripts/archive/**",
  ]),
  {
    // eslint-plugin-react-hooks 7 (with eslint-config-next 16) adds React Compiler rules, and
    // these v1 files break two of them. The Phase 5 redesign (plan U17 to U22) replaces the v1
    // UI, so they warn here instead of being rewritten twice. Every other file gets errors.
    files: [
      "src/components/map/MapContainer.tsx",
      "src/components/mobile/MobileBottomSheet.tsx",
      "src/components/mobile/MobileStationDetail.tsx",
      "src/components/station/StationDetailPanel.tsx",
      "src/components/theme/ThemeProvider.tsx",
      "src/components/ui/SmartTooltip.tsx",
      "src/hooks/useBodyScrollLock.ts",
      "src/hooks/useMediaQuery.ts",
    ],
    rules: {
      "react-hooks/refs": "warn",
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  {
    files: ["src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            serverOnly("lib/sync", "data sync"),
            serverOnly("lib/scoring", "score computation"),
            serverOnly("lib/narratives/generate", "narrative generation"),
            serverOnly("lib/prisma", "database client"),
            serverOnly("generated/prisma", "generated database client"),
          ],
        },
      ],
    },
  },
]);
