/**
 * The CTA "L" roster: every station with its CTA station id (the "map_id" in the CTA stop list
 * 8pix-ypme and the "station_id" in the ridership dataset 5neh-572f) and its name as stored in
 * Station.name in production. 144 stations as of the November 2025 stop list, State/Lake included
 * although it has been closed since 2026-01-05.
 *
 * Line membership is not repeated here: it is derived from the sequences in ./sequences.ts so the
 * two can never disagree.
 */
export interface RosterStation {
    ctaStationId: string;
    name: string;
}

export const CTA_ROSTER: readonly RosterStation[] = [
    { ctaStationId: "40830", name: "18th" },
    { ctaStationId: "41120", name: "35th-Bronzeville-IIT" },
    { ctaStationId: "40120", name: "35th/Archer" },
    { ctaStationId: "41270", name: "43rd" },
    { ctaStationId: "41080", name: "47th (Green)" },
    { ctaStationId: "41230", name: "47th (Red)" },
    { ctaStationId: "40130", name: "51st" },
    { ctaStationId: "40580", name: "54th/Cermak" },
    { ctaStationId: "40910", name: "63rd" },
    { ctaStationId: "40990", name: "69th" },
    { ctaStationId: "40240", name: "79th" },
    { ctaStationId: "41430", name: "87th" },
    { ctaStationId: "40450", name: "95th/Dan Ryan" },
    { ctaStationId: "40680", name: "Adams/Wabash" },
    { ctaStationId: "41240", name: "Addison (Blue)" },
    { ctaStationId: "41440", name: "Addison (Brown)" },
    { ctaStationId: "41420", name: "Addison (Red)" },
    { ctaStationId: "41200", name: "Argyle" },
    { ctaStationId: "40660", name: "Armitage (Brown/Purple)" },
    { ctaStationId: "40170", name: "Ashland (Green/Pink)" },
    { ctaStationId: "41060", name: "Ashland (Orange)" },
    { ctaStationId: "40290", name: "Ashland/63rd" },
    { ctaStationId: "40010", name: "Austin (Blue)" },
    { ctaStationId: "41260", name: "Austin (Green)" },
    { ctaStationId: "40060", name: "Belmont (Blue)" },
    { ctaStationId: "41320", name: "Belmont (Red/Brown/Purple)" },
    { ctaStationId: "40340", name: "Berwyn" },
    { ctaStationId: "41380", name: "Bryn Mawr" },
    { ctaStationId: "40570", name: "California (Blue)" },
    { ctaStationId: "41360", name: "California (Green)" },
    { ctaStationId: "40440", name: "California (Pink)" },
    { ctaStationId: "40280", name: "Central (Green)" },
    { ctaStationId: "41250", name: "Central (Purple)" },
    { ctaStationId: "40780", name: "Central Park" },
    { ctaStationId: "41000", name: "Cermak-Chinatown" },
    { ctaStationId: "41690", name: "Cermak-McCormick Place" },
    { ctaStationId: "41410", name: "Chicago (Blue)" },
    { ctaStationId: "40710", name: "Chicago (Brown/Purple)" },
    { ctaStationId: "41450", name: "Chicago (Red)" },
    { ctaStationId: "40970", name: "Cicero (Blue)" },
    { ctaStationId: "40480", name: "Cicero (Green)" },
    { ctaStationId: "40420", name: "Cicero (Pink)" },
    { ctaStationId: "40630", name: "Clark/Division" },
    { ctaStationId: "40380", name: "Clark/Lake" },
    { ctaStationId: "40430", name: "Clinton (Blue)" },
    { ctaStationId: "41160", name: "Clinton (Green/Pink)" },
    { ctaStationId: "41670", name: "Conservatory-Central Park Drive" },
    { ctaStationId: "40720", name: "Cottage Grove" },
    { ctaStationId: "40230", name: "Cumberland" },
    { ctaStationId: "40590", name: "Damen (Blue)" },
    { ctaStationId: "40090", name: "Damen (Brown)" },
    { ctaStationId: "41710", name: "Damen (Green)" },
    { ctaStationId: "40210", name: "Damen (Pink)" },
    { ctaStationId: "40050", name: "Davis" },
    { ctaStationId: "40690", name: "Dempster" },
    { ctaStationId: "40140", name: "Dempster-Skokie" },
    { ctaStationId: "40530", name: "Diversey (Brown/Purple)" },
    { ctaStationId: "40320", name: "Division" },
    { ctaStationId: "40390", name: "Forest Park" },
    { ctaStationId: "40520", name: "Foster" },
    { ctaStationId: "40870", name: "Francisco" },
    { ctaStationId: "41220", name: "Fullerton" },
    { ctaStationId: "40510", name: "Garfield (Green)" },
    { ctaStationId: "41170", name: "Garfield (Red)" },
    { ctaStationId: "40490", name: "Grand (Blue)" },
    { ctaStationId: "40330", name: "Grand (Red)" },
    { ctaStationId: "40760", name: "Granville" },
    { ctaStationId: "40940", name: "Halsted (Green)" },
    { ctaStationId: "41130", name: "Halsted (Orange)" },
    { ctaStationId: "40980", name: "Harlem" },
    { ctaStationId: "40750", name: "Harlem (O'Hare)" },
    { ctaStationId: "40020", name: "Harlem/Lake" },
    { ctaStationId: "40850", name: "Harold Washington Library-State/Van Buren" },
    { ctaStationId: "41490", name: "Harrison" },
    { ctaStationId: "40900", name: "Howard" },
    { ctaStationId: "40810", name: "Illinois Medical District" },
    { ctaStationId: "40300", name: "Indiana" },
    { ctaStationId: "40550", name: "Irving Park (Blue)" },
    { ctaStationId: "41460", name: "Irving Park (Brown)" },
    { ctaStationId: "40070", name: "Jackson (Blue)" },
    { ctaStationId: "40560", name: "Jackson (Red)" },
    { ctaStationId: "41190", name: "Jarvis" },
    { ctaStationId: "41280", name: "Jefferson Park Transit Center" },
    { ctaStationId: "41180", name: "Kedzie (Brown)" },
    { ctaStationId: "41070", name: "Kedzie (Green)" },
    { ctaStationId: "41150", name: "Kedzie (Orange)" },
    { ctaStationId: "41040", name: "Kedzie (Pink)" },
    { ctaStationId: "40250", name: "Kedzie-Homan" },
    { ctaStationId: "41290", name: "Kimball" },
    { ctaStationId: "41140", name: "King Drive" },
    { ctaStationId: "40600", name: "Kostner" },
    { ctaStationId: "41660", name: "Lake (Subway)" },
    { ctaStationId: "40700", name: "Laramie" },
    { ctaStationId: "41340", name: "LaSalle" },
    { ctaStationId: "40160", name: "LaSalle/Van Buren" },
    { ctaStationId: "40770", name: "Lawrence" },
    { ctaStationId: "41050", name: "Linden" },
    { ctaStationId: "41020", name: "Logan Square" },
    { ctaStationId: "41300", name: "Loyola" },
    { ctaStationId: "40270", name: "Main" },
    { ctaStationId: "40460", name: "Merchandise Mart (Brown/Purple)" },
    { ctaStationId: "40930", name: "Midway" },
    { ctaStationId: "40790", name: "Monroe (Blue)" },
    { ctaStationId: "41090", name: "Monroe (Red)" },
    { ctaStationId: "41330", name: "Montrose (Blue)" },
    { ctaStationId: "41500", name: "Montrose (Brown)" },
    { ctaStationId: "41510", name: "Morgan (Green/Pink)" },
    { ctaStationId: "40100", name: "Morse" },
    { ctaStationId: "40650", name: "North/Clybourn" },
    { ctaStationId: "40400", name: "Noyes" },
    { ctaStationId: "40890", name: "O'Hare" },
    { ctaStationId: "40180", name: "Oak Park (Blue)" },
    { ctaStationId: "41350", name: "Oak Park (Green)" },
    { ctaStationId: "41680", name: "Oakton-Skokie" },
    { ctaStationId: "41310", name: "Paulina" },
    { ctaStationId: "41030", name: "Polk" },
    { ctaStationId: "40920", name: "Pulaski (Blue)" },
    { ctaStationId: "40030", name: "Pulaski (Green)" },
    { ctaStationId: "40960", name: "Pulaski (Orange)" },
    { ctaStationId: "40150", name: "Pulaski (Pink)" },
    { ctaStationId: "40040", name: "Quincy" },
    { ctaStationId: "40470", name: "Racine" },
    { ctaStationId: "40610", name: "Ridgeland" },
    { ctaStationId: "41010", name: "Rockwell" },
    { ctaStationId: "41400", name: "Roosevelt" },
    { ctaStationId: "40820", name: "Rosemont" },
    { ctaStationId: "40800", name: "Sedgwick (Brown/Purple)" },
    { ctaStationId: "40080", name: "Sheridan" },
    { ctaStationId: "40840", name: "South Boulevard" },
    { ctaStationId: "40360", name: "Southport" },
    { ctaStationId: "40190", name: "Sox-35th" },
    { ctaStationId: "40260", name: "State/Lake" },
    { ctaStationId: "40880", name: "Thorndale" },
    { ctaStationId: "40350", name: "UIC-Halsted" },
    { ctaStationId: "40370", name: "Washington" },
    { ctaStationId: "41700", name: "Washington/Wabash" },
    { ctaStationId: "40730", name: "Washington/Wells" },
    { ctaStationId: "41210", name: "Wellington (Brown/Purple)" },
    { ctaStationId: "40220", name: "Western" },
    { ctaStationId: "41480", name: "Western (Brown)" },
    { ctaStationId: "40670", name: "Western (O'Hare)" },
    { ctaStationId: "40310", name: "Western (Orange)" },
    { ctaStationId: "40740", name: "Western (Pink)" },
    { ctaStationId: "40540", name: "Wilson" },
];

const BY_ID = new Map(CTA_ROSTER.map((s) => [s.ctaStationId, s]));

export function rosterStation(ctaStationId: string): RosterStation | undefined {
    return BY_ID.get(ctaStationId);
}
