/**
 * The score v2 acceptance oracle (U12): the cleaned snapshot, data through 2025-11-30, loaded
 * into a scratch city in the test database, scored by the same read, compute, and write path a
 * sync run uses. It checks the audit's named expectations (docs/audit-2026-10-02/ghost-score.md
 * section 5.2) on the data they were made from.
 *
 * Three of them do not follow from the design the plan adopted, and Nate chose to keep the design
 * (R14's weights, KTD8's Loop peers) and pin what it produces instead (2026-10-03):
 * - Wilson is not fading. Its year-over-year decline is in the top tenth, probably riders going
 *   back to Lawrence after it reopened, but it carries about twice its neighbors' riders, and the
 *   residual (45%) outweighs year-over-year (25%).
 * - LaSalle/Van Buren and Library stay fading. They are the two smallest Loop stations and KTD8
 *   compares Loop stations with the other Loop stations. LaSalle/Van Buren is growing, so it
 *   carries the "small but growing" badge beside its tier.
 *
 * The fixture is a trimmed export of that snapshot, regenerated by scripts/extract-score-snapshot.ts.
 * Western (O'Hare) 40670, Western (Orange) 40310, and State/Lake 40260 are absent from it by
 * design (KTD3: the Westerns' snapshot history is misattributed, and State/Lake was never
 * ingested), so the city here has the other 141 stations.
 *
 * SCORE_SNAPSHOT_REPORT=1 prints the full ranking with its component percentiles.
 */
import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { STATION_CLOSURES } from "@/lib/cta/closures";
import { CTA_ROSTER } from "@/lib/cta/roster";
import { linesForStation } from "@/lib/cta/sequences";
import { prisma } from "@/lib/prisma";
import { deleteSyncTestCity, stationIdFor } from "@/lib/sync/__fixtures__/db";
import { writeStationMetrics } from "@/lib/sync/baseMetrics";
import type { RidershipRow } from "@/lib/sync/match";
import type { DayType } from "@/lib/sync/socrata";
import { computeStationMetrics } from "@/lib/sync/run";
import { deriveStationStatuses } from "@/lib/sync/status";
import { upsertRidership } from "@/lib/sync/upsert";
import { smallStationBadge } from "./score";

const CITY = "test-score-snapshot";
const DATA_THROUGH = "2025-11-30";
const FIXTURE = new URL("./__fixtures__/snapshot-2025-11-30.csv.gz", import.meta.url);

const TOP_TIER = ["40940", "41140", "40600", "40300"]; // Halsted (Green), King Drive, Kostner, Indiana
const EVANSTON_PURPLE = ["41050", "41250", "40400", "40520", "40050", "40690", "40270", "40840"]; // Linden to South Boulevard
const LASALLE_VAN_BUREN = "40160";
const LIBRARY = "40850";
const WILSON = "40540";
const ABSENT = ["40670", "40310", "40260"];

function fixtureRows(): RidershipRow[] {
    const [header, ...lines] = gunzipSync(readFileSync(FIXTURE)).toString("utf8").trim().split("\n");
    expect(header).toBe("ctaStationId,serviceDate,entries,dayType");
    return lines.map((line) => {
        const [ctaStationId, serviceDate, entries, dayType] = line.split(",");
        return { stationId: stationIdFor(CITY, ctaStationId), serviceDate, entries: Number(entries), dayType: dayType as DayType };
    });
}

type MetricsRow = Awaited<ReturnType<typeof readMetrics>>[number];
let metrics: MetricsRow[];
const byCta = (cta: string) => metrics.find((m) => m.station.ctaStationId === cta);
const nameOf = (cta: string) => CTA_ROSTER.find((s) => s.ctaStationId === cta)?.name ?? cta;
const tierOf = (cta: string) => byCta(cta)?.tier;

/** A station's score and component row, the evidence a failing expectation is judged by. */
function componentRow(cta: string): string {
    const m = byCta(cta);
    if (!m) return `${nameOf(cta)}: no metrics row`;
    const pct = (v: number | null) => (v === null ? "null" : v.toFixed(1));
    return (
        `${nameOf(cta)}: score ${m.ghostScore} ${m.tier} rank ${m.rank}/${m.rankedCount}; ` +
        `residual ${pct(m.residualPct)} (avg12m ${m.avg12m?.toFixed(0)} vs baseline ${m.baselineAvg?.toFixed(0)}), ` +
        `yoy ${pct(m.yoyPct)} (${m.yoyChangePct?.toFixed(1)}%), longRun ${pct(m.longRunPct)} (${m.vs2019Pct?.toFixed(1)}%), ` +
        `erratic ${pct(m.erraticPct)}`
    );
}

async function readMetrics() {
    return prisma.stationMetrics.findMany({
        where: { station: { city: { code: CITY } } },
        include: { station: { select: { ctaStationId: true } } },
    });
}

beforeAll(async () => {
    await deleteSyncTestCity(CITY);
    const rows = fixtureRows();
    const present = new Set(rows.map((r) => r.stationId));
    const city = await prisma.city.create({ data: { code: CITY, name: "Score snapshot oracle" } });
    const stations = CTA_ROSTER.filter((s) => present.has(stationIdFor(CITY, s.ctaStationId)));
    await prisma.station.createMany({
        data: stations.map((s) => ({
            id: stationIdFor(CITY, s.ctaStationId),
            cityId: city.id,
            externalId: s.ctaStationId,
            ctaStationId: s.ctaStationId,
            name: s.name,
            latitude: 41.88,
            longitude: -87.63,
            lines: JSON.stringify(linesForStation(s.ctaStationId)),
            openedAt: s.openedAt ? new Date(`${s.openedAt}T00:00:00Z`) : null,
        })),
    });
    await prisma.stationClosure.createMany({
        data: STATION_CLOSURES.filter((c) => present.has(stationIdFor(CITY, c.ctaStationId))).map((c) => ({
            stationId: stationIdFor(CITY, c.ctaStationId),
            startDate: new Date(`${c.startDate}T00:00:00Z`),
            endDate: c.endDate ? new Date(`${c.endDate}T00:00:00Z`) : null,
            reason: c.reason,
        })),
    });
    await upsertRidership(prisma, rows);

    const statuses = await deriveStationStatuses(prisma, city.id, DATA_THROUGH);
    const scored = await computeStationMetrics(prisma, city.id, DATA_THROUGH, statuses);
    await prisma.$transaction((tx) => writeStationMetrics(tx, scored, DATA_THROUGH, new Date()));
    metrics = await readMetrics();

    if (process.env.SCORE_SNAPSHOT_REPORT) printRanking();
}, 180_000);

afterAll(async () => {
    await deleteSyncTestCity(CITY);
    await prisma.$disconnect();
});

describe("score v2 on the snapshot (data through 2025-11-30)", () => {
    it("loads the 141 snapshot stations, without the two Westerns or State/Lake", () => {
        expect(metrics).toHaveLength(141);
        for (const cta of ABSENT) expect(byCta(cta)).toBeUndefined();
    });

    it("ranks every ranked station once, from 1 to the ranked count, and scores span 0 to 100", () => {
        const ranked = metrics.filter((m) => m.rank !== null);
        expect(ranked.map((m) => m.rank).sort((a, b) => a! - b!)).toEqual(Array.from({ length: ranked.length }, (_, i) => i + 1));
        for (const m of metrics) {
            expect(m.rankedCount).toBe(ranked.length);
            expect(m.scoreVersion).toBe(2);
        }
        expect(Math.max(...ranked.map((m) => m.ghostScore))).toBe(100);
        expect(Math.min(...ranked.map((m) => m.ghostScore))).toBe(0);
    });

    it("ranks reopened Lawrence and Berwyn, with no 12-month comparisons yet", () => {
        for (const cta of ["40770", "40340"]) {
            expect(byCta(cta)).toMatchObject({ residualPct: null, longRunPct: null, yoyPct: null });
            expect(byCta(cta)?.rank).not.toBeNull();
        }
    });

    it.each(TOP_TIER)("puts %s in the ghost tier", (cta) => {
        expect(tierOf(cta), componentRow(cta)).toBe("GHOST");
    });

    it.each(EVANSTON_PURPLE)("keeps Evanston Purple station %s out of the ghost tier", (cta) => {
        expect(tierOf(cta), componentRow(cta)).toBeDefined();
        expect(tierOf(cta), componentRow(cta)).not.toBe("GHOST");
    });

    it("rates LaSalle/Van Buren and Library fading against the Loop, and LaSalle/Van Buren small but growing", () => {
        for (const cta of [LASALLE_VAN_BUREN, LIBRARY]) {
            const m = byCta(cta);
            expect(m?.tier, componentRow(cta)).toBe("FADING");
            expect(m?.residualPct, componentRow(cta)).toBeGreaterThanOrEqual(75);
            expect((m?.peerStationIds as { basis?: string } | null)?.basis).toBe("loop");
        }
        expect(smallStationBadge(byCta(LASALLE_VAN_BUREN)!), componentRow(LASALLE_VAN_BUREN)).toBe("small-but-growing");
    });

    it("shows Wilson's year-over-year decline in the top tenth while its ridership keeps it healthy", () => {
        const m = byCta(WILSON);
        expect(m?.yoyPct, componentRow(WILSON)).toBeGreaterThanOrEqual(90);
        expect(m?.residualPct, componentRow(WILSON)).toBeLessThan(25);
        expect(m?.tier, componentRow(WILSON)).toBe("HEALTHY");
    });
});

function printRanking(): void {
    const fmt = (v: number | null) => (v === null ? "-" : v.toFixed(0));
    const rows = [...metrics]
        .sort((a, b) => (a.rank ?? 1e9) - (b.rank ?? 1e9))
        .map((m) => ({
            rank: m.rank,
            station: nameOf(m.station.ctaStationId!),
            score: m.ghostScore,
            tier: m.tier,
            residual: fmt(m.residualPct),
            yoy: fmt(m.yoyPct),
            longRun: fmt(m.longRunPct),
            erratic: fmt(m.erraticPct),
            avg12m: fmt(m.avg12m),
            baseline: fmt(m.baselineAvg),
            yoyChange: m.yoyChangePct === null ? "-" : m.yoyChangePct.toFixed(1),
            vs2019: m.vs2019Pct === null ? "-" : m.vs2019Pct.toFixed(1),
            peers: ((m.peerStationIds as { basis?: string; ctaStationIds?: string[] } | null)?.ctaStationIds ?? []).map(nameOf).join(" / "),
        }));
    console.table(rows);
}
